services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: barthez
      POSTGRES_PASSWORD: Barthezpassword1234
      POSTGRES_DB: blogDB
